include: package:flutter_lints/flutter.yaml

# Keep project-specific analyzer settings minimal to avoid duplicate/unknown rules
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

# Add any custom lints below. Leave empty to inherit defaults from flutter_lints.
linter:
  rules: {}
