name: mobile_grok
description: A Flutter app for activity management with AI integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # HTTP Requests
  http: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_slidable: ^4.0.1
  intl: ^0.20.2
  file_picker: ^10.3.2
  
  # Notifications
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
